# Generated by Django 5.1.3 on 2024-11-18 13:33

import django.core.validators
import django.db.models.deletion
import easy_thumbnails.fields
import ephios_material_checklists.models.checklist
import ephios_material_checklists.models.itemtype
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ephios_material_checklists", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=254, unique=True, verbose_name="Name"),
                ),
                (
                    "deprecated",
                    models.BooleanField(default=False, verbose_name="Ausgesondert"),
                ),
                (
                    "abstract",
                    models.BooleanField(
                        default=False, verbose_name="only sub-checklist"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=ephios_material_checklists.models.checklist.checklist_file_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                        verbose_name="PDF-Datei",
                    ),
                ),
                (
                    "image",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        blank=True,
                        upload_to=ephios_material_checklists.models.checklist.checklist_image_path,
                        verbose_name="Bild",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checkliste",
                "verbose_name_plural": "Checklisten",
            },
        ),
        migrations.CreateModel(
            name="ChecklistCompartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254, verbose_name="Name")),
                (
                    "image",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        blank=True,
                        upload_to=ephios_material_checklists.models.checklist.checklist_compartment_image_path,
                        verbose_name="Bild",
                    ),
                ),
                (
                    "parent_checklist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compartments",
                        to="ephios_material_checklists.checklist",
                        verbose_name="übergeordnete Checkliste",
                    ),
                ),
                (
                    "parent_compartment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_compartments",
                        to="ephios_material_checklists.checklistcompartment",
                        verbose_name="übergeordnetes Fach",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklisten-Fach",
                "verbose_name_plural": "Checklisten-Fächer",
                "ordering": ("name",),
            },
        ),
        migrations.AlterModelOptions(
            name="itemtype",
            options={
                "ordering": ("category__order_key", "category__name", "name"),
                "verbose_name": "Materialtyp",
                "verbose_name_plural": "Materialtypen",
            },
        ),
        migrations.AlterModelOptions(
            name="itemtypecategory",
            options={
                "ordering": ("order_key", "name"),
                "verbose_name": "Materialtyp-Kategorie",
                "verbose_name_plural": "Materialtyp-Kategorien",
            },
        ),
        migrations.AlterField(
            model_name="itemtype",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="ephios_material_checklists.itemtypecategory",
                verbose_name="Kategorie",
            ),
        ),
        migrations.AlterField(
            model_name="itemtype",
            name="deprecated",
            field=models.BooleanField(default=False, verbose_name="Ausgesondert"),
        ),
        migrations.AlterField(
            model_name="itemtype",
            name="image",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True,
                upload_to=ephios_material_checklists.models.itemtype.item_type_image_path,
                verbose_name="Bild",
            ),
        ),
        migrations.AlterField(
            model_name="itemtype",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Bemerkungen"),
        ),
        migrations.AlterField(
            model_name="itemtypecategory",
            name="order_key",
            field=models.IntegerField(default=1, verbose_name="Sortierschlüssel"),
        ),
        migrations.CreateModel(
            name="ChecklistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="required amount",
                    ),
                ),
                (
                    "optional",
                    models.BooleanField(default=False, verbose_name="optional"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Bemerkungen")),
                (
                    "compartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="ephios_material_checklists.checklistcompartment",
                        verbose_name="compartment",
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ephios_material_checklists.itemtype",
                        verbose_name="item type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklisten-Eintrag",
                "verbose_name_plural": "Checklisten-Einträge",
            },
        ),
        migrations.CreateModel(
            name="ChecklistCompartmentWithExternalChecklist",
            fields=[
                (
                    "checklistcompartment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ephios_material_checklists.checklistcompartment",
                    ),
                ),
                (
                    "external_checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ephios_material_checklists.checklist",
                        verbose_name="referenzierte Checkliste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklisten-Fach gemäß anderer Checkliste",
                "verbose_name_plural": "Checklisten-Facher gemäß anderen Checklisten",
            },
            bases=("ephios_material_checklists.checklistcompartment",),
        ),
        migrations.AddConstraint(
            model_name="checklistcompartment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent_compartment__isnull", True)),
                fields=("name", "parent_checklist"),
                name="name_is_unique_in_checklist",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistcompartment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent_checklist__isnull", True)),
                fields=("name", "parent_compartment"),
                name="name_is_unique_in_compartment",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="checklistentry",
            unique_together={("compartment", "item_type")},
        ),
    ]
