# Generated by Django 5.1.3 on 2025-03-29 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ephios_material_checklists", "0002_checklist_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemtype",
            name="category",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="ephios_material_checklists.itemtypecategory",
                verbose_name="Kategorie",
            ),
        ),
    ]
